export const COPY = {
  pt: {
    title: 'Você contra a mosca', subtitle: 'Mundo contínuo. Um chinelo por vez.', lab: 'Laboratório', science: 'Ciência & FAQ',
    intro: 'Mire enquanto ela se move. Arraste, puxe para dar força e solte para arremessar. Um toque curto empurra objetos. Depois, veja se foi erro de mira ou se o movimento da mosca evitou o impacto.',
    loading: "Carregando e verificando o conectoma integral (~31 MB)…", ready: 'Tudo pronto. Só começa quando você entrar.', enter: 'Entrar no jogo',
    aim: 'Mire seu próximo arremesso', flight: 'Chinelo no ar', result: 'Preparando a próxima tentativa', paused: 'Pausado', replaying: 'Repetição · não conta no placar',
    hint: 'Arraste para mirar; puxe para baixo para dar força. Solte para lançar. Fora da cena cancela.',
    buttonHint: 'Arraste para mirar e use Arremessar. Toque curto num objeto para empurrá-lo.',
    gestures: 'Soltar o gesto para arremessar', release: 'Solte para arremessar',
    objectsNote: 'Toque curto em vasos, caneca, garrafa ou balde para empurrar. O chinelo também os derruba. Móveis e paredes são fixos. Colisores e tombamento são aproximações, não física calibrada.',
    fallen: 'Objetos tombados', tidy: 'Arrumar o pátio',
    direction: 'Direção', power: 'Força', elevation: 'Inclinação', throw: 'Arremessar', pause: 'Pausar', resume: 'Retomar', replay: 'Ver de novo',
    hits: 'Acertos', dodges: 'Esquivas', misses: 'Erros de mira', attempts: 'Arremessos',
    hit: 'Você acertou', dodge: 'Ela escapou da trajetória', miss: 'Não atingiria a mosca imóvel',
    waiting: "Ela escolhe as ações de voo e navegação. Você escolhe quando arremessar.",
    reward: 'Recompensa de treino', learned: 'Usada no aprendizado', frozen: 'Política congelada',
    learning: 'Aprender entre arremessos', learningNote: "Ligado desde o início. Aprende com fuga e navegação, e salva neste navegador. Atualiza os dois controladores motores, não as sinapses anatômicas. Desligue para uma avaliação congelada. Mais treino não garante melhora.",
    cinematic: 'Câmera cinematográfica após lançar', intense: 'Impacto estilizado verde', brainSample: "O brilho mostra atividade calculada, não todos os neurônios acesos ao mesmo tempo. Toda a rede está disponível; só células que respondem ao estímulo disparam. A visualização resume até 1.400 células acima do limiar de atividade. Os 27 atributos geométricos são entradas adicionais do controlador.",
    trained: 'Episódios de aprendizado', memory: 'Memória deste modo', saved: 'Salvo neste navegador', ephemeral: 'Ainda sem aprendizado salvo',
    export: 'Exportar backup', import: 'Importar backup', reset: 'Recomeçar pré-treinada', blank: 'Começar sem treino',
    confirmReset: 'Substituir apenas o aprendizado e o placar do modo jogável? Laboratório e palpites não serão alterados. Exporte antes se quiser guardar esta mosca.',
    confirmImport: 'Substituir apenas o modo jogável por este backup?',
    saveError: 'Não foi possível salvar. A sessão foi pausada; exporte um backup. Se outra aba mudou o jogo, recarregue antes de continuar.',
    error: "Não foi possível carregar ou executar o modo escolhido. Nenhum outro cérebro foi usado no lugar. Tente novamente ou escolha explicitamente outro modo.",
    memoryNote: "Full e Light têm aprendizado e placar separados neste navegador. O aprendizado Full existente e os saves antigos são preservados. Importações devem corresponder ao perfil escolhido. Exportar permite guardar uma cópia; recarregar descarta a tentativa e arruma os objetos.",
    method: 'Como isso é decidido?', methodText: 'A mão fica em um ponto fixo do pátio. A mira por toque ajusta direção e inclinação; os controles permitem ajuste manual. A linha e o chinelo usam o mesmo integrador e os mesmos obstáculos. “Esquiva” compara o lançamento com uma mosca imóvel no ponto inicial; não prova que a política causou a fuga. Ela já podia estar andando ou voando.',
    senses: 'Ela não lê sua mira', sensesText: "São 49 atributos da atividade neural e 27 sinais construídos: geometria observada, movimento anterior, corpo, obstáculos, bordas e objetivo de navegação. Ela não recebe sua mira, força nem trajetória futura. A política escolhe entre 12 ações; sustentação e objetivos são abstrações de jogo, não biologia validada.",
    brainTitle: 'Atividade neural', brainBenchmark: 'Custo neural · JSON', research: 'Pesquisa e limites ↗', evaluation: 'Treino e avaliação', evaluationText: "Os pesos herdados vêm do treino anterior com {episodes} episódios. O relatório anterior usava uma rede filtrada: seus resultados não avaliam este conectoma integral. O aprendizado durante o jogo continua disponível, mas ainda não há uma avaliação de desempenho reservada para esta configuração. Veja o benchmark de custo e as limitações.",
    report: 'Relatório e pesos publicados', audit: 'Código do treino', controls: 'Controles', resumeHint: 'Retome para arremessar.',
    flightTitle: "VOO AUTÔNOMO · V2",
    brainMode: "Circuito de controle",
    escapeMode: "Recorte de fuga · leve",
    wholeMode: "Full · conectoma integral dos dados",
    neuralStatus: "Rede carregada e verificada: {n} neurônios · {e} pares.",
    escapeNote: "6.203 neurônios · 108.237 pares conectados. Controla voo e navegação; não reproduz toda a inteligência da mosca.",
    wholeNote: "138.639 neurônios · 15.091.983 pares · 54.492.922 sinapses agregadas. Todas as conexões do arquivo v783, sem corte de pares fracos ou teto nos pesos. Sem substituição por recorte. Modelo experimental, não toda a biologia.",
    altitude: "Altura",
    decision: "Ação",
    goals: "Objetivos alcançados",
    targetHeight: "Altura do objetivo",
    navigationNote: "Objetivos 3D sorteados orientam o treino de exploração. Aproximar e alcançar rende recompensa; o controlador decide as ações, inclusive subir e pousar. Limite físico: 6 unidades de cena, não metros.",
    legacy: "Trazer aprendizado do modo anterior",
    noLegacy: "Não há um save anterior neste navegador. Você também pode importar um backup.",
    confirmLegacy: "Transferir pesos anteriores para este corpo novo? O placar deste perfil será zerado, e seu save antigo ficará intacto. A transferência não garante desempenho. Exporte o perfil atual antes de substituí-lo.",
    brainProvenance: "Posições e pares conectados vêm dos dados v783; linhas não são axônios nem locais individuais de sinapses. A simulação usa todos os pares do arquivo, inclusive os de uma sinapse. O inspetor mostra até 160 conexões da seleção para legibilidade, consultadas na mesma rede do simulador. Atividade calculada, não registrada de um animal.",
    actionNames: ["manter altura / frear","inclinar à esquerda","inclinar à direita","decolar","avançar","virar à esquerda","virar à direita","pousar","subir","descer","deslocar à esquerda","deslocar à direita"],
    stay: "Continuar neste modo",
    chooseTitle: "Como você quer jogar?",
    chooseNote: "Escolha antes de baixar o conectoma. Full é o padrão; nunca trocamos seu cérebro automaticamente.",
    fullChoice: "Full · maior fidelidade aos dados",
    fullSummary: "138.639 neurônios · 15,1 milhões de pares · ~31 MB",
    lightChoice: "Light · menor consumo",
    lightSummary: "138.639 neurônios · 2,7 milhões de pares · ~6,8 MB",
    profileWarning: "Light mantém a lista de neurônios, mas remove pares com menos de 5 sinapses e limita cada peso a 127 sinapses. Isso muda a rede e pode mudar o comportamento. Full não garante mais inteligência. Ambos permitem aprendizado motor.",
    graphics: "Qualidade gráfica",
    standardGraphics: "Padrão · sombras e mais definição",
    lightGraphics: "Leve · sem sombras, menor resolução",
    graphicsNote: "Gráficos leves não alteram o cérebro, a física nem o aprendizado. Experimente Full + gráficos leves no celular.",
    remember: "Lembrar minhas escolhas",
    preferencesError: "Não foi possível lembrar a preferência. Você ainda pode jogar.",
    download: "Carregar modo escolhido",
    chooseStatus: "O conectoma só será baixado depois da sua escolha.",
    loadingLight: "Carregando e verificando o conectoma Light (~6,8 MB)…",
    changeSetup: "Trocar Full / Light",
    changeConfirm: "Trocar de modo recarrega a página e descarta a tentativa atual. O aprendizado já salvo de cada perfil fica preservado. Continuar?",
    retry: "Tentar novamente / mudar escolhas",
    lightMode: "Light · conectoma filtrado",
    lightNote: "138.639 neurônios · 2.700.513 pares. Pacote histórico: apenas pares com ≥5 sinapses, pesos limitados a 127. Algumas células ficam desconectadas. Experimental, não toda a biologia.",
    lightProvenance: "Posições e pares vêm dos dados v783. No Light, pares com menos de 5 sinapses são removidos e pesos têm teto de 127. O inspetor consulta essa mesma rede filtrada e mostra até 160 conexões por seleção. Linhas não são axônios; atividade simulada, não registrada de um animal.",
    lightEvaluation: "Os pesos herdados vêm do treino anterior com {episodes} episódios. O relatório do perfil amplo usa esta rede filtrada como transferência, não como treino integral feito nela. Os resultados são históricos; a sessão atual e seu aprendizado precisam de nova avaliação reservada.",
  },
  en: {
    title: 'You versus the fly', subtitle: 'A continuous world. One slipper at a time.', lab: 'Laboratory', science: 'Science & FAQ',
    intro: 'Aim while she moves. Drag, pull for power and release to throw. A short tap nudges objects. Then see whether you missed or her movement avoided contact.',
    loading: "Loading and verifying the complete connectome (~31 MB)…", ready: 'Ready. Nothing starts until you enter.', enter: 'Enter the game',
    aim: 'Aim your next throw', flight: 'Slipper in flight', result: 'Preparing the next attempt', paused: 'Paused', replaying: 'Replay · does not affect score',
    hint: 'Drag to aim; pull down for power. Release to throw. Release outside the scene to cancel.',
    buttonHint: 'Drag to aim, then use Throw. Tap an object to nudge it.',
    gestures: 'Release gesture to throw', release: 'Release to throw',
    objectsNote: 'Tap pots, the mug, bottle or bucket to nudge them. Slipper impacts can knock them over too. Furniture and walls are fixed. Colliders and tipping are approximations, not calibrated physics.',
    fallen: 'Objects knocked over', tidy: 'Tidy the courtyard',
    direction: 'Direction', power: 'Power', elevation: 'Elevation', throw: 'Throw', pause: 'Pause', resume: 'Resume', replay: 'Watch again',
    hits: 'Hits', dodges: 'Dodges', misses: 'Aim misses', attempts: 'Throws',
    hit: 'You hit her', dodge: 'She escaped the trajectory', miss: 'Would miss an immobile fly',
    waiting: "She chooses flight and navigation actions. You choose when to throw.",
    reward: 'Training reward', learned: 'Used for learning', frozen: 'Frozen policy',
    learning: 'Learn between throws', learningNote: "Enabled initially. Learns escape and navigation and saves in this browser. Updates both motor controllers, not anatomical synapses. Disable for frozen evaluation. More training does not guarantee improvement.",
    cinematic: 'Cinematic camera after throwing', intense: 'Stylized green impact', brainSample: "Glow displays computed activity, not every neuron firing together. The entire network is available; responding cells spike. Visualization summarizes up to 1,400 cells above an activity threshold. The 27 geometry features are additional controller inputs.",
    trained: 'Learning episodes', memory: 'This mode’s memory', saved: 'Saved in this browser', ephemeral: 'No learning saved yet',
    export: 'Export backup', import: 'Import backup', reset: 'Restart pretrained', blank: 'Start untrained',
    confirmReset: 'Replace only the playable mode’s learning and score? The laboratory and predictions will not change. Export first to keep this fly.',
    confirmImport: 'Replace only the playable mode with this backup?',
    saveError: 'Could not save. Paused; export a backup. If another tab changed the game, reload before continuing.',
    error: "Could not load or run the selected mode. No other brain was substituted. Retry or explicitly choose another mode.",
    memoryNote: "Full and Light keep separate learning and scores in this browser. Existing Full learning and legacy saves are preserved. Imports must match the selected profile. Export to keep a copy; reloading discards the throw and tidies props.",
    method: 'How is this decided?', methodText: 'The hand stays at a fixed courtyard location. Touch aiming adjusts direction and elevation; sliders allow manual adjustment. The guide and projectile share the integrator and obstacles. A “dodge” compares the throw against a fly held still at its starting position; it does not prove the policy caused the escape. She may already have been walking or flying.',
    senses: 'She cannot read your aim', sensesText: "49 neural activity features plus 27 constructed signals: observed geometry, past movement, body, obstacles, boundaries and navigation goal. No aim, power or future trajectory is supplied. The policy chooses among 12 actions; lift and goals are game abstractions, not validated biology.",
    brainTitle: 'Neural activity', brainBenchmark: 'Neural cost · JSON', research: 'Research and limitations ↗', evaluation: 'Training and evaluation', evaluationText: "Inherited weights come from the earlier {episodes}-episode training. That report used filtered wiring: its results do not evaluate this complete connectome. In-game learning remains available, but this configuration does not yet have a held-out performance evaluation. See the cost benchmark and limitations.",
    report: 'Published report and weights', audit: 'Training code', controls: 'Controls', resumeHint: 'Resume to throw.',
    flightTitle: "AUTONOMOUS FLIGHT · V2",
    brainMode: "Control circuit",
    escapeMode: "Escape subcircuit · lightweight",
    wholeMode: "Full · complete source connectome",
    neuralStatus: "Loaded and verified: {n} neurons · {e} pairs.",
    escapeNote: "6,203 neurons · 108,237 connected pairs. Controls flight and navigation, not the fly’s complete intelligence.",
    wholeNote: "138,639 neurons · 15,091,983 pairs · 54,492,922 aggregated synapses. Every connection in the v783 file, without weak-pair pruning or weight caps. No subcircuit substitution. Experimental model, not complete biology.",
    altitude: "Height",
    decision: "Action",
    goals: "Goals reached",
    targetHeight: "Goal height",
    navigationNote: "Random 3D goals guide exploration training. Progress and arrival earn rewards; the controller chooses actions, including climbing and landing. Physical ceiling: 6 scene units, not meters.",
    legacy: "Transfer learning from the old mode",
    noLegacy: "No old save exists in this browser. You can also import a backup.",
    confirmLegacy: "Transfer old weights to the new body? This profile’s score resets; the old save remains intact. Performance is not guaranteed. Export this profile before replacing it.",
    brainProvenance: "Positions and connected pairs come from v783 data; lines are not axons or individual synapse locations. Simulation retains every source pair, including single-synapse pairs. The inspector shows up to 160 selected connections for legibility, queried from the same simulation graph. Activity is computed, not recorded from an animal.",
    actionNames: ["hover / brake","lean left","lean right","take off","forward","turn left","turn right","land","climb","descend","strafe left","strafe right"],
    stay: "Stay in this mode",
    chooseTitle: "How would you like to play?",
    chooseNote: "Choose before downloading the connectome. Full is the default; we never switch your brain automatically.",
    fullChoice: "Full · closer to the source data",
    fullSummary: "138,639 neurons · 15.1 million pairs · ~31 MB",
    lightChoice: "Light · lower resource use",
    lightSummary: "138,639 neurons · 2.7 million pairs · ~6.8 MB",
    profileWarning: "Light keeps the neuron list but removes pairs with fewer than 5 synapses and caps each weight at 127 synapses. This changes wiring and may change behavior. Full does not guarantee more intelligence. Both support motor learning.",
    graphics: "Graphics quality",
    standardGraphics: "Standard · shadows and more detail",
    lightGraphics: "Light · no shadows, lower resolution",
    graphicsNote: "Light graphics do not change the brain, physics or learning. Try Full + light graphics on mobile.",
    remember: "Remember my choices",
    preferencesError: "Could not remember this preference. You can still play.",
    download: "Load selected mode",
    chooseStatus: "The connectome is downloaded only after your choice.",
    loadingLight: "Loading and verifying the Light connectome (~6.8 MB)…",
    changeSetup: "Switch Full / Light",
    changeConfirm: "Switching reloads the page and discards the current throw. Saved learning for each profile stays intact. Continue?",
    retry: "Try again / change choices",
    lightMode: "Light · filtered connectome",
    lightNote: "138,639 neurons · 2,700,513 pairs. Historical package: pairs with ≥5 synapses only, weights capped at 127. Some cells become disconnected. Experimental, not complete biology.",
    lightProvenance: "Positions and pairs come from v783 data. Light removes pairs with fewer than 5 synapses and caps weights at 127. The inspector queries this same filtered graph and displays up to 160 selected connections. Lines are not axons; activity is simulated, not recorded from an animal.",
    lightEvaluation: "Inherited weights come from earlier training with {episodes} episodes. The wider-profile report uses this filtered graph as a transfer, not as training performed entirely on it. Results are historical; this session and its learning need new held-out evaluation.",
  },
  es: {
    title: 'Tú contra la mosca', subtitle: 'Mundo continuo. Una chancla a la vez.', lab: 'Laboratorio', science: 'Ciencia & FAQ',
    intro: 'Apunta mientras se mueve. Arrastra, tira para dar fuerza y suelta para lanzar. Un toque corto empuja objetos. Después, descubre si fallaste o si su movimiento evitó el impacto.',
    loading: "Cargando y verificando el conectoma íntegro (~31 MB)…", ready: 'Todo listo. Solo empieza cuando entres.', enter: 'Entrar al juego',
    aim: 'Apunta tu próximo lanzamiento', flight: 'Chancla en el aire', result: 'Preparando el siguiente intento', paused: 'En pausa', replaying: 'Repetición · no modifica el marcador',
    hint: 'Arrastra para apuntar; tira hacia abajo para dar fuerza. Suelta para lanzar; fuera de la escena cancela.',
    buttonHint: 'Arrastra para apuntar y usa Lanzar. Toca un objeto para empujarlo.',
    gestures: 'Soltar el gesto para lanzar', release: 'Suelta para lanzar',
    objectsNote: 'Toca macetas, taza, botella o cubo para empujar. La chancla también puede volcarlos. Muebles y paredes son fijos. Los colisionadores y vuelcos son aproximaciones, no física calibrada.',
    fallen: 'Objetos volcados', tidy: 'Ordenar el patio',
    direction: 'Dirección', power: 'Fuerza', elevation: 'Inclinación', throw: 'Lanzar', pause: 'Pausar', resume: 'Continuar', replay: 'Ver de nuevo',
    hits: 'Aciertos', dodges: 'Esquivas', misses: 'Fallos de puntería', attempts: 'Lanzamientos',
    hit: 'Acertaste', dodge: 'Escapó de la trayectoria', miss: 'No alcanzaría a la mosca inmóvil',
    waiting: "Ella elige acciones de vuelo y navegación. Tú decides cuándo lanzar.",
    reward: 'Recompensa de entrenamiento', learned: 'Usada para aprender', frozen: 'Política congelada',
    learning: 'Aprender entre lanzamientos', learningNote: "Activado al inicio. Aprende escape y navegación y guarda en este navegador. Actualiza ambos controladores motores, no las sinapsis anatómicas. Desactívalo para evaluar sin aprendizaje. Más entrenamiento no garantiza mejoras.",
    cinematic: 'Cámara cinematográfica después de lanzar', intense: 'Impacto verde estilizado', brainSample: "El brillo muestra actividad calculada, no todas las neuronas disparando juntas. Toda la red está disponible; disparan las células que responden. Se resumen hasta 1.400 células sobre el umbral de actividad. Los 27 atributos geométricos son entradas adicionales del controlador.",
    trained: 'Episodios de aprendizaje', memory: 'Memoria de este modo', saved: 'Guardado en este navegador', ephemeral: 'Sin aprendizaje guardado',
    export: 'Exportar copia', import: 'Importar copia', reset: 'Reiniciar preentrenada', blank: 'Empezar sin entrenar',
    confirmReset: '¿Sustituir solo el aprendizaje y marcador del modo jugable? Laboratorio y pronósticos no cambiarán. Exporta antes si quieres conservar esta mosca.',
    confirmImport: '¿Sustituir solo el modo jugable con esta copia?',
    saveError: 'No se pudo guardar. En pausa; exporta una copia. Si otra pestaña cambió el juego, recarga antes de continuar.',
    error: "No se pudo cargar o ejecutar el modo elegido. No se sustituyó por otro cerebro. Reintenta o elige otro modo explícitamente.",
    memoryNote: "Full y Light guardan aprendizaje y marcadores separados en este navegador. Se conservan el aprendizaje Full existente y las copias antiguas. La importación debe corresponder al perfil. Exporta para guardar una copia; recargar descarta el lanzamiento y ordena objetos.",
    method: '¿Cómo se decide?', methodText: 'La mano permanece en un punto fijo del patio. El gesto ajusta dirección e inclinación; los controles permiten ajuste manual. Guía y chancla comparten integrador y obstáculos. Una “esquiva” compara el lanzamiento con una mosca inmóvil en la posición inicial; no demuestra que la política causara la huida. Ya podía estar caminando o volando.',
    senses: 'No lee tu puntería', sensesText: "49 atributos de actividad neural y 27 señales construidas: geometría observada, movimiento pasado, cuerpo, obstáculos, límites y objetivo. No recibe puntería, fuerza ni trayectoria futura. La política elige entre 12 acciones; sustentación y objetivos son abstracciones de juego, no biología validada.",
    brainTitle: 'Actividad neural', brainBenchmark: 'Coste neural · JSON', research: 'Investigación y límites ↗', evaluation: 'Entrenamiento y evaluación', evaluationText: "Los pesos heredados proceden del entrenamiento anterior de {episodes} episodios. Ese informe usaba una red filtrada: sus resultados no evalúan este conectoma íntegro. El aprendizaje en juego continúa, pero esta configuración aún no tiene evaluación reservada de rendimiento. Consulta el benchmark de coste y las limitaciones.",
    report: 'Informe y pesos publicados', audit: 'Código de entrenamiento', controls: 'Controles', resumeHint: 'Continúa para lanzar.',
    flightTitle: "VUELO AUTÓNOMO · V2",
    brainMode: "Circuito de control",
    escapeMode: "Subcircuito de escape · ligero",
    wholeMode: "Full · conectoma íntegro de los datos",
    neuralStatus: "Red cargada y verificada: {n} neuronas · {e} pares.",
    escapeNote: "6.203 neuronas · 108.237 pares conectados. Controla vuelo y navegación; no reproduce toda la inteligencia.",
    wholeNote: "138.639 neuronas · 15.091.983 pares · 54.492.922 sinapsis agregadas. Todas las conexiones del archivo v783, sin poda de pares débiles ni límite de peso. Sin sustitución por subcircuitos. Modelo experimental, no toda la biología.",
    altitude: "Altura",
    decision: "Acción",
    goals: "Objetivos alcanzados",
    targetHeight: "Altura del objetivo",
    navigationNote: "Objetivos 3D aleatorios guían el entrenamiento de exploración. Acercarse y llegar da recompensas; el controlador elige acciones, incluyendo subir y aterrizar. Límite: 6 unidades de escena, no metros.",
    legacy: "Traer aprendizaje del modo anterior",
    noLegacy: "No hay copia anterior en este navegador. También puedes importar un archivo.",
    confirmLegacy: "¿Transferir pesos al cuerpo nuevo? Reinicia el marcador de este perfil; conserva la copia antigua. El rendimiento no está garantizado. Exporta este perfil antes de sustituirlo.",
    brainProvenance: "Posiciones y pares conectados provienen de v783; las líneas no son axones ni posiciones individuales de sinapsis. Se simulan todos los pares del archivo, incluidos los de una sinapsis. El inspector muestra hasta 160 conexiones para legibilidad, consultadas en la misma red simulada. Actividad calculada, no registrada de un animal.",
    actionNames: ["mantener altura / frenar","inclinar izquierda","inclinar derecha","despegar","avanzar","girar izquierda","girar derecha","aterrizar","subir","bajar","desplazar izquierda","desplazar derecha"],
    stay: "Seguir en este modo",
    chooseTitle: "¿Cómo quieres jugar?",
    chooseNote: "Elige antes de descargar el conectoma. Full es el predeterminado; nunca cambiamos el cerebro automáticamente.",
    fullChoice: "Full · mayor fidelidad a los datos",
    fullSummary: "138.639 neuronas · 15,1 millones de pares · ~31 MB",
    lightChoice: "Light · menor consumo",
    lightSummary: "138.639 neuronas · 2,7 millones de pares · ~6,8 MB",
    profileWarning: "Light conserva la lista de neuronas, pero elimina pares con menos de 5 sinapsis y limita cada peso a 127 sinapsis. Cambia la red y puede cambiar el comportamiento. Full no garantiza más inteligencia. Ambos permiten aprendizaje motor.",
    graphics: "Calidad gráfica",
    standardGraphics: "Estándar · sombras y más definición",
    lightGraphics: "Ligera · sin sombras, menor resolución",
    graphicsNote: "Los gráficos ligeros no cambian el cerebro, la física ni el aprendizaje. Prueba Full + gráficos ligeros en el móvil.",
    remember: "Recordar mis elecciones",
    preferencesError: "No se pudo recordar la preferencia. Aún puedes jugar.",
    download: "Cargar modo elegido",
    chooseStatus: "El conectoma solo se descarga después de elegir.",
    loadingLight: "Cargando y verificando el conectoma Light (~6,8 MB)…",
    changeSetup: "Cambiar Full / Light",
    changeConfirm: "Cambiar recarga la página y descarta el lanzamiento actual. El aprendizaje guardado de cada perfil se conserva. ¿Continuar?",
    retry: "Reintentar / cambiar elecciones",
    lightMode: "Light · conectoma filtrado",
    lightNote: "138.639 neuronas · 2.700.513 pares. Paquete histórico: pares con ≥5 sinapsis, pesos limitados a 127. Algunas células quedan desconectadas. Experimental, no toda la biología.",
    lightProvenance: "Posiciones y pares provienen de v783. Light elimina pares con menos de 5 sinapsis y limita pesos a 127. El inspector consulta esa misma red filtrada y muestra hasta 160 conexiones por selección. Las líneas no son axones; actividad simulada, no registrada de un animal.",
    lightEvaluation: "Los pesos heredados proceden de {episodes} episodios anteriores. El informe amplio usa esta red filtrada como transferencia, no como entrenamiento íntegro en ella. Son resultados históricos; esta sesión y su aprendizaje necesitan nueva evaluación reservada.",
  },
};
