export const COPY = {
  pt: {
    title: 'Você contra a mosca', subtitle: 'Mundo contínuo. Um chinelo por vez.', lab: 'Laboratório', science: 'Ciência & FAQ',
    intro: 'Mire enquanto ela se move. Arraste, puxe para dar força e solte para arremessar. Um toque curto empurra objetos. Depois, veja se foi erro de mira ou se o movimento da mosca evitou o impacto.',
    loading: 'Preparando o pátio e a política treinada…', ready: 'Tudo pronto. Só começa quando você entrar.', enter: 'Entrar no jogo',
    aim: 'Mire seu próximo arremesso', flight: 'Chinelo no ar', result: 'Preparando a próxima tentativa', paused: 'Pausado', replaying: 'Repetição · não conta no placar',
    hint: 'Arraste para mirar; puxe para baixo para dar força. Solte para lançar. Fora da cena cancela.',
    buttonHint: 'Arraste para mirar e use Arremessar. Toque curto num objeto para empurrá-lo.',
    gestures: 'Soltar o gesto para arremessar', release: 'Solte para arremessar',
    objectsNote: 'Toque curto em vasos, caneca, garrafa ou balde para empurrar. O chinelo também os derruba. Móveis e paredes são fixos. Colisores e tombamento são aproximações, não física calibrada.',
    fallen: 'Objetos tombados', tidy: 'Arrumar o pátio',
    direction: 'Direção', power: 'Força', elevation: 'Inclinação', throw: 'Arremessar', pause: 'Pausar', resume: 'Retomar', replay: 'Ver de novo',
    hits: 'Acertos', dodges: 'Esquivas', misses: 'Erros de mira', attempts: 'Arremessos',
    hit: 'Você acertou', dodge: 'Ela escapou da trajetória', miss: 'Não atingiria a mosca imóvel',
    waiting: "Ela escolhe as ações de voo e navegação. Você escolhe quando arremessar.",
    reward: 'Recompensa de treino', learned: 'Usada no aprendizado', frozen: 'Política congelada',
    learning: 'Aprender entre arremessos', learningNote: "Ligado desde o início. Aprende com arremessos e pequenos episódios de navegação; explorar pode causar erros. Lotes de 8. Desligue para congelar todos os pesos. Não altera laboratório ou saves antigos.",
    cinematic: 'Câmera cinematográfica após lançar', intense: 'Impacto estilizado verde', brainSample: "Atividade simulada da observação atual, inclusive durante a exploração. O brilho não representa os 27 atributos geométricos e de navegação adicionados.",
    trained: 'Episódios de aprendizado', memory: 'Memória deste modo', saved: 'Salvo neste navegador', ephemeral: 'Ainda sem aprendizado salvo',
    export: 'Exportar backup', import: 'Importar backup', reset: 'Recomeçar pré-treinada', blank: 'Começar sem treino',
    confirmReset: 'Substituir apenas o aprendizado e o placar do modo jogável? Laboratório e palpites não serão alterados. Exporte antes se quiser guardar esta mosca.',
    confirmImport: 'Substituir apenas o modo jogável por este backup?',
    saveError: 'Não foi possível salvar. A sessão foi pausada; exporte um backup. Se outra aba mudou o jogo, recarregue antes de continuar.',
    error: 'Não foi possível concluir. Recarregue e tente novamente.',
    memoryNote: "Voo v2 tem saves separados por cérebro; o modo anterior permanece guardado. Importar pesos antigos transfere parâmetros, mas reinicia o placar e o otimizador: as ações mudaram. Exporte antes de substituir. Recarregar descarta a tentativa e arruma os objetos.",
    method: 'Como isso é decidido?', methodText: 'A mão fica em um ponto fixo do pátio. A mira por toque ajusta direção e inclinação; os controles permitem ajuste manual. A linha e o chinelo usam o mesmo integrador e os mesmos obstáculos. “Esquiva” compara o lançamento com uma mosca imóvel no ponto inicial; não prova que a política causou a fuga. Ela já podia estar andando ou voando.',
    senses: 'Ela não lê sua mira', sensesText: "São 49 atributos da atividade neural e 27 sinais construídos: geometria observada, movimento anterior, corpo, obstáculos, bordas e objetivo de navegação. Ela não recebe sua mira, força nem trajetória futura. A política escolhe entre 12 ações; sustentação e objetivos são abstrações de jogo, não biologia validada.",
    brainTitle: 'Atividade neural', brainBenchmark: 'Custo neural · JSON', research: 'Pesquisa e limites ↗', evaluation: 'Treino e avaliação', evaluationText: "Pacote com {episodes} episódios, incluindo treino herdado. Neste perfil: {hits} impactos em {total} arremessos reservados; {dodges} de {threats} ameaças evitadas. Pesos congelados, alturas e posições variadas. Este benchmark usa origens de lançamento variadas, não só a mão fixa do jogo atual. Cérebro amplo usa transferência dos pesos do recorte, não treino completo próprio. Resultados exploratórios; consulte controles e limitações no relatório.",
    report: 'Relatório e pesos publicados', audit: 'Código do treino', controls: 'Controles', resumeHint: 'Retome para arremessar.',
    flightTitle: "VOO AUTÔNOMO · V2",
    brainMode: "Circuito de controle",
    escapeMode: "Recorte de fuga · leve",
    wholeMode: "Cérebro amplo · padrão",
    escapeNote: "6.203 neurônios · 108.237 pares conectados. Controla voo e navegação; não reproduz toda a inteligência da mosca.",
    wholeNote: "Experimental. 138.639 neurônios · 2.700.513 pares, filtrados em ≥5 sinapses. Executa o conjunto cerebral maior com pesos motores transferidos. Pode ficar lento no celular; save independente. Não inclui toda a biologia nem todas as sinapses.",
    altitude: "Altura",
    decision: "Ação",
    goals: "Objetivos alcançados",
    targetHeight: "Altura do objetivo",
    navigationNote: "Objetivos 3D sorteados orientam o treino de exploração. Aproximar e alcançar rende recompensa; o controlador decide as ações, inclusive subir e pousar. Limite físico: 6 unidades de cena, não metros.",
    legacy: "Trazer aprendizado do modo anterior",
    noLegacy: "Não há um save anterior neste navegador. Você também pode importar um backup.",
    confirmLegacy: "Transferir pesos anteriores para este corpo novo? O placar deste perfil será zerado, e seu save antigo ficará intacto. A transferência não garante desempenho. Exporte o perfil atual antes de substituí-lo.",
    brainProvenance: "Pontos são posições de células anotadas; linhas são pares conectados registrados, não axônios nem locais individuais de sinapses. O perfil amplo usa o pacote FlyWire 783 filtrado em ≥5 sinapses; o recorte usa ≥8. A atividade é simulada, a anatomia permanece fixa.",
    actionNames: ["manter altura / frear","inclinar à esquerda","inclinar à direita","decolar","avançar","virar à esquerda","virar à direita","pousar","subir","descer","deslocar à esquerda","deslocar à direita"],
  },
  en: {
    title: 'You versus the fly', subtitle: 'A continuous world. One slipper at a time.', lab: 'Laboratory', science: 'Science & FAQ',
    intro: 'Aim while she moves. Drag, pull for power and release to throw. A short tap nudges objects. Then see whether you missed or her movement avoided contact.',
    loading: 'Preparing the courtyard and trained policy…', ready: 'Ready. Nothing starts until you enter.', enter: 'Enter the game',
    aim: 'Aim your next throw', flight: 'Slipper in flight', result: 'Preparing the next attempt', paused: 'Paused', replaying: 'Replay · does not affect score',
    hint: 'Drag to aim; pull down for power. Release to throw. Release outside the scene to cancel.',
    buttonHint: 'Drag to aim, then use Throw. Tap an object to nudge it.',
    gestures: 'Release gesture to throw', release: 'Release to throw',
    objectsNote: 'Tap pots, the mug, bottle or bucket to nudge them. Slipper impacts can knock them over too. Furniture and walls are fixed. Colliders and tipping are approximations, not calibrated physics.',
    fallen: 'Objects knocked over', tidy: 'Tidy the courtyard',
    direction: 'Direction', power: 'Power', elevation: 'Elevation', throw: 'Throw', pause: 'Pause', resume: 'Resume', replay: 'Watch again',
    hits: 'Hits', dodges: 'Dodges', misses: 'Aim misses', attempts: 'Throws',
    hit: 'You hit her', dodge: 'She escaped the trajectory', miss: 'Would miss an immobile fly',
    waiting: "She chooses flight and navigation actions. You choose when to throw.",
    reward: 'Training reward', learned: 'Used for learning', frozen: 'Frozen policy',
    learning: 'Learn between throws', learningNote: "On from the start. Learns from throws and short navigation episodes; exploration can cause mistakes. Batches of 8. Switch off to freeze all weights. Laboratory and old saves remain unchanged.",
    cinematic: 'Cinematic camera after throwing', intense: 'Stylized green impact', brainSample: "Simulated activity from the current observation, including exploration. Glow does not represent the 27 added geometry/navigation features.",
    trained: 'Learning episodes', memory: 'This mode’s memory', saved: 'Saved in this browser', ephemeral: 'No learning saved yet',
    export: 'Export backup', import: 'Import backup', reset: 'Restart pretrained', blank: 'Start untrained',
    confirmReset: 'Replace only the playable mode’s learning and score? The laboratory and predictions will not change. Export first to keep this fly.',
    confirmImport: 'Replace only the playable mode with this backup?',
    saveError: 'Could not save. Paused; export a backup. If another tab changed the game, reload before continuing.',
    error: 'Could not complete this action. Reload and try again.',
    memoryNote: "Flight v2 has separate saves per brain; the old mode remains stored. Importing old weights resets score and optimizer because actions changed. Export before replacing. Reload resets the current throw and props.",
    method: 'How is this decided?', methodText: 'The hand stays at a fixed courtyard location. Touch aiming adjusts direction and elevation; sliders allow manual adjustment. The guide and projectile share the integrator and obstacles. A “dodge” compares the throw against a fly held still at its starting position; it does not prove the policy caused the escape. She may already have been walking or flying.',
    senses: 'She cannot read your aim', sensesText: "49 neural activity features plus 27 constructed signals: observed geometry, past movement, body, obstacles, boundaries and navigation goal. No aim, power or future trajectory is supplied. The policy chooses among 12 actions; lift and goals are game abstractions, not validated biology.",
    brainTitle: 'Neural activity', brainBenchmark: 'Neural cost · JSON', research: 'Research and limitations ↗', evaluation: 'Training and evaluation', evaluationText: "Package with {episodes} episodes, including inherited training. This profile: {hits} hits across {total} held-out throws; {dodges} of {threats} threats avoided. Frozen weights, varied heights/positions. This benchmark uses varied launch origins, not only the fixed hand in the current game. The wider brain transfers weights trained on the subcircuit, without its own full retraining. Exploratory results; see report controls and limitations.",
    report: 'Published report and weights', audit: 'Training code', controls: 'Controls', resumeHint: 'Resume to throw.',
    flightTitle: "AUTONOMOUS FLIGHT · V2",
    brainMode: "Control circuit",
    escapeMode: "Escape subcircuit · lightweight",
    wholeMode: "Wider brain · default",
    escapeNote: "6,203 neurons · 108,237 connected pairs. Controls flight and navigation, not the fly’s complete intelligence.",
    wholeNote: "Experimental. 138,639 neurons · 2,700,513 pairs, filtered at ≥5 synapses. Runs the wider brain package with transferred motor weights. May be slow on mobile; separate save. Not every synapse or biological mechanism is included.",
    altitude: "Height",
    decision: "Action",
    goals: "Goals reached",
    targetHeight: "Goal height",
    navigationNote: "Random 3D goals guide exploration training. Progress and arrival earn rewards; the controller chooses actions, including climbing and landing. Physical ceiling: 6 scene units, not meters.",
    legacy: "Transfer learning from the old mode",
    noLegacy: "No old save exists in this browser. You can also import a backup.",
    confirmLegacy: "Transfer old weights to the new body? This profile’s score resets; the old save remains intact. Performance is not guaranteed. Export this profile before replacing it.",
    brainProvenance: "Dots are annotated cell positions; lines are recorded connected pairs, not axons or individual synapse sites. The wider profile uses FlyWire 783 filtered at ≥5 synapses; the subcircuit at ≥8. Activity is simulated; anatomy stays fixed.",
    actionNames: ["hover / brake","lean left","lean right","take off","forward","turn left","turn right","land","climb","descend","strafe left","strafe right"],
  },
  es: {
    title: 'Tú contra la mosca', subtitle: 'Mundo continuo. Una chancla a la vez.', lab: 'Laboratorio', science: 'Ciencia & FAQ',
    intro: 'Apunta mientras se mueve. Arrastra, tira para dar fuerza y suelta para lanzar. Un toque corto empuja objetos. Después, descubre si fallaste o si su movimiento evitó el impacto.',
    loading: 'Preparando el patio y la política entrenada…', ready: 'Todo listo. Solo empieza cuando entres.', enter: 'Entrar al juego',
    aim: 'Apunta tu próximo lanzamiento', flight: 'Chancla en el aire', result: 'Preparando el siguiente intento', paused: 'En pausa', replaying: 'Repetición · no modifica el marcador',
    hint: 'Arrastra para apuntar; tira hacia abajo para dar fuerza. Suelta para lanzar; fuera de la escena cancela.',
    buttonHint: 'Arrastra para apuntar y usa Lanzar. Toca un objeto para empujarlo.',
    gestures: 'Soltar el gesto para lanzar', release: 'Suelta para lanzar',
    objectsNote: 'Toca macetas, taza, botella o cubo para empujar. La chancla también puede volcarlos. Muebles y paredes son fijos. Los colisionadores y vuelcos son aproximaciones, no física calibrada.',
    fallen: 'Objetos volcados', tidy: 'Ordenar el patio',
    direction: 'Dirección', power: 'Fuerza', elevation: 'Inclinación', throw: 'Lanzar', pause: 'Pausar', resume: 'Continuar', replay: 'Ver de nuevo',
    hits: 'Aciertos', dodges: 'Esquivas', misses: 'Fallos de puntería', attempts: 'Lanzamientos',
    hit: 'Acertaste', dodge: 'Escapó de la trayectoria', miss: 'No alcanzaría a la mosca inmóvil',
    waiting: "Ella elige acciones de vuelo y navegación. Tú decides cuándo lanzar.",
    reward: 'Recompensa de entrenamiento', learned: 'Usada para aprender', frozen: 'Política congelada',
    learning: 'Aprender entre lanzamientos', learningNote: "Activado desde el inicio. Aprende con lanzamientos y episodios cortos de navegación; explorar puede provocar errores. Lotes de 8. Desactiva para congelar todos los pesos. No altera laboratorio ni copias antiguas.",
    cinematic: 'Cámara cinematográfica después de lanzar', intense: 'Impacto verde estilizado', brainSample: "Actividad simulada de la observación actual, incluso al explorar. El brillo no representa los 27 atributos geométricos y de navegación añadidos.",
    trained: 'Episodios de aprendizaje', memory: 'Memoria de este modo', saved: 'Guardado en este navegador', ephemeral: 'Sin aprendizaje guardado',
    export: 'Exportar copia', import: 'Importar copia', reset: 'Reiniciar preentrenada', blank: 'Empezar sin entrenar',
    confirmReset: '¿Sustituir solo el aprendizaje y marcador del modo jugable? Laboratorio y pronósticos no cambiarán. Exporta antes si quieres conservar esta mosca.',
    confirmImport: '¿Sustituir solo el modo jugable con esta copia?',
    saveError: 'No se pudo guardar. En pausa; exporta una copia. Si otra pestaña cambió el juego, recarga antes de continuar.',
    error: 'No se pudo completar. Recarga e inténtalo de nuevo.',
    memoryNote: "Vuelo v2 guarda cada cerebro por separado; el modo anterior permanece almacenado. Importar pesos antiguos reinicia marcador y optimizador porque cambiaron las acciones. Exporta antes de sustituir. Recargar reinicia intento y objetos.",
    method: '¿Cómo se decide?', methodText: 'La mano permanece en un punto fijo del patio. El gesto ajusta dirección e inclinación; los controles permiten ajuste manual. Guía y chancla comparten integrador y obstáculos. Una “esquiva” compara el lanzamiento con una mosca inmóvil en la posición inicial; no demuestra que la política causara la huida. Ya podía estar caminando o volando.',
    senses: 'No lee tu puntería', sensesText: "49 atributos de actividad neural y 27 señales construidas: geometría observada, movimiento pasado, cuerpo, obstáculos, límites y objetivo. No recibe puntería, fuerza ni trayectoria futura. La política elige entre 12 acciones; sustentación y objetivos son abstracciones de juego, no biología validada.",
    brainTitle: 'Actividad neural', brainBenchmark: 'Coste neural · JSON', research: 'Investigación y límites ↗', evaluation: 'Entrenamiento y evaluación', evaluationText: "Paquete con {episodes} episodios, incluido entrenamiento heredado. Este perfil: {hits} impactos en {total} lanzamientos reservados; {dodges} de {threats} amenazas evitadas. Pesos congelados, alturas y posiciones variadas. Este benchmark usa orígenes variados, no solo la mano fija del juego actual. El cerebro amplio transfiere pesos del subcircuito, sin entrenamiento completo propio. Resultados exploratorios; consulta controles y limitaciones.",
    report: 'Informe y pesos publicados', audit: 'Código de entrenamiento', controls: 'Controles', resumeHint: 'Continúa para lanzar.',
    flightTitle: "VUELO AUTÓNOMO · V2",
    brainMode: "Circuito de control",
    escapeMode: "Subcircuito de escape · ligero",
    wholeMode: "Cerebro amplio · predeterminado",
    escapeNote: "6.203 neuronas · 108.237 pares conectados. Controla vuelo y navegación; no reproduce toda la inteligencia.",
    wholeNote: "Experimental. 138.639 neuronas · 2.700.513 pares, filtrados en ≥5 sinapsis. Ejecuta el paquete cerebral amplio con pesos motores transferidos. Puede ser lento en móvil; copia independiente. No incluye toda la biología ni todas las sinapsis.",
    altitude: "Altura",
    decision: "Acción",
    goals: "Objetivos alcanzados",
    targetHeight: "Altura del objetivo",
    navigationNote: "Objetivos 3D aleatorios guían el entrenamiento de exploración. Acercarse y llegar da recompensas; el controlador elige acciones, incluyendo subir y aterrizar. Límite: 6 unidades de escena, no metros.",
    legacy: "Traer aprendizaje del modo anterior",
    noLegacy: "No hay copia anterior en este navegador. También puedes importar un archivo.",
    confirmLegacy: "¿Transferir pesos al cuerpo nuevo? Reinicia el marcador de este perfil; conserva la copia antigua. El rendimiento no está garantizado. Exporta este perfil antes de sustituirlo.",
    brainProvenance: "Puntos: posiciones celulares anotadas. Líneas: pares conectados registrados, no axones ni ubicaciones individuales de sinapsis. Perfil amplio: FlyWire 783 filtrado en ≥5 sinapsis; subcircuito: ≥8. Actividad simulada, anatomía fija.",
    actionNames: ["mantener altura / frenar","inclinar izquierda","inclinar derecha","despegar","avanzar","girar izquierda","girar derecha","aterrizar","subir","bajar","desplazar izquierda","desplazar derecha"],
  },
};
