export const COPY = {
  pt: {
    title: 'Você contra a mosca', subtitle: 'Mundo contínuo. Um chinelo por vez.', lab: 'Laboratório', science: 'Ciência & FAQ',
    intro: 'Mire enquanto ela se move. Arraste, puxe para dar força e solte para arremessar. Um toque curto empurra objetos. Depois, veja se foi erro de mira ou se o movimento da mosca evitou o impacto.',
    loading: 'Preparando o pátio e a política treinada…', ready: 'Tudo pronto. Só começa quando você entrar.', enter: 'Entrar no jogo',
    aim: 'Mire seu próximo arremesso', flight: 'Chinelo no ar', result: 'Preparando a próxima tentativa', paused: 'Pausado', replaying: 'Repetição · não conta no placar',
    hint: 'Arraste para mirar; puxe para baixo para dar força. Solte para lançar. Fora da cena cancela.',
    buttonHint: 'Arraste para mirar e use Arremessar. Toque curto num objeto para empurrá-lo.',
    gestures: 'Soltar o gesto para arremessar', release: 'Solte para arremessar',
    objectsNote: 'Toque curto em vasos, caneca, garrafa ou balde para empurrar. O chinelo também os derruba. Móveis e paredes são fixos. Colisores e tombamento são aproximações, não física calibrada.',
    fallen: 'Objetos tombados', tidy: 'Arrumar o pátio',
    direction: 'Direção', power: 'Força', elevation: 'Inclinação', throw: 'Arremessar', pause: 'Pausar', resume: 'Retomar', replay: 'Ver de novo',
    hits: 'Acertos', dodges: 'Esquivas', misses: 'Erros de mira', attempts: 'Arremessos',
    hit: 'Você acertou', dodge: 'Ela escapou da trajetória', miss: 'Não atingiria a mosca imóvel',
    waiting: 'Você escolhe quando lançar. O movimento livre é encenado; a reação usa uma política aprendida.',
    reward: 'Recompensa de treino', learned: 'Usada no aprendizado', frozen: 'Política congelada',
    learning: 'Aprender entre arremessos', learningNote: 'Ligado desde o início. Ela explora ações e pode errar enquanto aprende. Atualizações em lotes de 8 após o resultado. Desligue para avaliar pesos congelados. Não altera laboratório nem palpites.',
    cinematic: 'Câmera cinematográfica após lançar', intense: 'Impacto estilizado verde', brainSample: 'Atividade simulada da última observação durante o arremesso. O brilho não representa os 8 atributos extras do controlador.',
    trained: 'Episódios de aprendizado', memory: 'Memória deste modo', saved: 'Salvo neste navegador', ephemeral: 'Ainda sem arremessos salvos',
    export: 'Exportar backup', import: 'Importar backup', reset: 'Recomeçar pré-treinada', blank: 'Começar sem treino',
    confirmReset: 'Substituir apenas o aprendizado e o placar do modo jogável? Laboratório e palpites não serão alterados. Exporte antes se quiser guardar esta mosca.',
    confirmImport: 'Substituir apenas o modo jogável por este backup?',
    saveError: 'Não foi possível salvar. A sessão foi pausada; exporte um backup. Se outra aba mudou o jogo, recarregue antes de continuar.',
    error: 'Não foi possível concluir. Recarregue e tente novamente.',
    memoryNote: 'Seu aprendizado salvo é preservado nas atualizações. Para usar o pacote novo, exporte antes e escolha Recomeçar pré-treinada: isso substitui pesos e placar, com confirmação. Recarregar descarta a tentativa e arruma os objetos. Backups são separados do laboratório.',
    method: 'Como isso é decidido?', methodText: 'A linha e o chinelo usam o mesmo integrador e os mesmos obstáculos. “Esquiva” compara o lançamento com uma mosca imóvel no ponto inicial; não prova que a política causou a fuga. Ela já podia estar andando ou voando.',
    senses: 'Ela não lê sua mira', sensesText: 'O controlador recebe 49 atributos de atividade no circuito FlyWire e 8 medidas visuais/corporais construídas, calculadas a partir do presente e do passado. Não recebe força, mira nem a trajetória futura. A animação livre é programada; a física e o controlador não são uma mosca biologicamente validada.',
    evaluation: 'Treino e avaliação', evaluationText: 'Pacote com {episodes} episódios de treino. Em {total} lançamentos reservados por controlador, sofreu {hits} impactos, contra {previousHits} da versão anterior. Das {threats} ameaças, evitou {dodges}; versão anterior: {previous}; ações aleatórias: {random}. Pesos congelados, uma semente de treino, sem movimento inicial. Resultado exploratório, não garantia no jogo nem validação biológica.',
    report: 'Relatório e pesos publicados', audit: 'Código do treino', controls: 'Controles', resumeHint: 'Retome para arremessar.',
  },
  en: {
    title: 'You versus the fly', subtitle: 'A continuous world. One slipper at a time.', lab: 'Laboratory', science: 'Science & FAQ',
    intro: 'Aim while she moves. Drag, pull for power and release to throw. A short tap nudges objects. Then see whether you missed or her movement avoided contact.',
    loading: 'Preparing the courtyard and trained policy…', ready: 'Ready. Nothing starts until you enter.', enter: 'Enter the game',
    aim: 'Aim your next throw', flight: 'Slipper in flight', result: 'Preparing the next attempt', paused: 'Paused', replaying: 'Replay · does not affect score',
    hint: 'Drag to aim; pull down for power. Release to throw. Release outside the scene to cancel.',
    buttonHint: 'Drag to aim, then use Throw. Tap an object to nudge it.',
    gestures: 'Release gesture to throw', release: 'Release to throw',
    objectsNote: 'Tap pots, the mug, bottle or bucket to nudge them. Slipper impacts can knock them over too. Furniture and walls are fixed. Colliders and tipping are approximations, not calibrated physics.',
    fallen: 'Objects knocked over', tidy: 'Tidy the courtyard',
    direction: 'Direction', power: 'Power', elevation: 'Elevation', throw: 'Throw', pause: 'Pause', resume: 'Resume', replay: 'Watch again',
    hits: 'Hits', dodges: 'Dodges', misses: 'Aim misses', attempts: 'Throws',
    hit: 'You hit her', dodge: 'She escaped the trajectory', miss: 'Would miss an immobile fly',
    waiting: 'You choose when to throw. Free movement is scripted; reactions use a learned policy.',
    reward: 'Training reward', learned: 'Used for learning', frozen: 'Frozen policy',
    learning: 'Learn between throws', learningNote: 'On from the start. Exploring actions can cause mistakes while learning. Updates in batches of 8 after outcomes. Switch off to evaluate frozen weights. Does not change laboratory or predictions.',
    cinematic: 'Cinematic camera after throwing', intense: 'Stylized green impact', brainSample: 'Simulated activity from the latest observation during a throw. Glow does not represent the controller’s 8 extra features.',
    trained: 'Learning episodes', memory: 'This mode’s memory', saved: 'Saved in this browser', ephemeral: 'No throws saved yet',
    export: 'Export backup', import: 'Import backup', reset: 'Restart pretrained', blank: 'Start untrained',
    confirmReset: 'Replace only the playable mode’s learning and score? The laboratory and predictions will not change. Export first to keep this fly.',
    confirmImport: 'Replace only the playable mode with this backup?',
    saveError: 'Could not save. Paused; export a backup. If another tab changed the game, reload before continuing.',
    error: 'Could not complete this action. Reload and try again.',
    memoryNote: 'Updates preserve your saved learning. To use the new package, export first and choose Restart pretrained: it replaces weights and score after confirmation. Reloading discards the current throw and resets objects. Backups are separate from the laboratory.',
    method: 'How is this decided?', methodText: 'The guide and projectile share the integrator and obstacles. A “dodge” compares the throw against a fly held still at its starting position; it does not prove the policy caused the escape. She may already have been walking or flying.',
    senses: 'She cannot read your aim', sensesText: 'The controller receives 49 activity features from the FlyWire circuit and 8 constructed visual/body measurements computed from the present and past. No power, aim or future trajectory is supplied. Free movement is scripted; physics and controller are not a biologically validated fly.',
    evaluation: 'Training and evaluation', evaluationText: 'Package with {episodes} training episodes. Across {total} held-out throws per controller, it took {hits} hits, versus {previousHits} for the previous version. Of {threats} threats, it avoided {dodges}; previous version: {previous}; random actions: {random}. Frozen weights, one training seed, no initial movement. Exploratory results, not a gameplay guarantee or biological validation.',
    report: 'Published report and weights', audit: 'Training code', controls: 'Controls', resumeHint: 'Resume to throw.',
  },
  es: {
    title: 'Tú contra la mosca', subtitle: 'Mundo continuo. Una chancla a la vez.', lab: 'Laboratorio', science: 'Ciencia & FAQ',
    intro: 'Apunta mientras se mueve. Arrastra, tira para dar fuerza y suelta para lanzar. Un toque corto empuja objetos. Después, descubre si fallaste o si su movimiento evitó el impacto.',
    loading: 'Preparando el patio y la política entrenada…', ready: 'Todo listo. Solo empieza cuando entres.', enter: 'Entrar al juego',
    aim: 'Apunta tu próximo lanzamiento', flight: 'Chancla en el aire', result: 'Preparando el siguiente intento', paused: 'En pausa', replaying: 'Repetición · no modifica el marcador',
    hint: 'Arrastra para apuntar; tira hacia abajo para dar fuerza. Suelta para lanzar; fuera de la escena cancela.',
    buttonHint: 'Arrastra para apuntar y usa Lanzar. Toca un objeto para empujarlo.',
    gestures: 'Soltar el gesto para lanzar', release: 'Suelta para lanzar',
    objectsNote: 'Toca macetas, taza, botella o cubo para empujar. La chancla también puede volcarlos. Muebles y paredes son fijos. Los colisionadores y vuelcos son aproximaciones, no física calibrada.',
    fallen: 'Objetos volcados', tidy: 'Ordenar el patio',
    direction: 'Dirección', power: 'Fuerza', elevation: 'Inclinación', throw: 'Lanzar', pause: 'Pausar', resume: 'Continuar', replay: 'Ver de nuevo',
    hits: 'Aciertos', dodges: 'Esquivas', misses: 'Fallos de puntería', attempts: 'Lanzamientos',
    hit: 'Acertaste', dodge: 'Escapó de la trayectoria', miss: 'No alcanzaría a la mosca inmóvil',
    waiting: 'Tú eliges cuándo lanzar. El movimiento libre está programado; la reacción usa una política aprendida.',
    reward: 'Recompensa de entrenamiento', learned: 'Usada para aprender', frozen: 'Política congelada',
    learning: 'Aprender entre lanzamientos', learningNote: 'Activado desde el inicio. Explorar acciones puede causar errores al aprender. Actualizaciones en lotes de 8 tras el resultado. Desactívalo para evaluar pesos congelados. No cambia laboratorio ni pronósticos.',
    cinematic: 'Cámara cinematográfica después de lanzar', intense: 'Impacto verde estilizado', brainSample: 'Actividad simulada de la última observación durante el lanzamiento. El brillo no representa los 8 atributos adicionales del controlador.',
    trained: 'Episodios de aprendizaje', memory: 'Memoria de este modo', saved: 'Guardado en este navegador', ephemeral: 'Sin lanzamientos guardados',
    export: 'Exportar copia', import: 'Importar copia', reset: 'Reiniciar preentrenada', blank: 'Empezar sin entrenar',
    confirmReset: '¿Sustituir solo el aprendizaje y marcador del modo jugable? Laboratorio y pronósticos no cambiarán. Exporta antes si quieres conservar esta mosca.',
    confirmImport: '¿Sustituir solo el modo jugable con esta copia?',
    saveError: 'No se pudo guardar. En pausa; exporta una copia. Si otra pestaña cambió el juego, recarga antes de continuar.',
    error: 'No se pudo completar. Recarga e inténtalo de nuevo.',
    memoryNote: 'Las actualizaciones conservan tu aprendizaje. Para usar el paquete nuevo, exporta antes y elige Reiniciar preentrenada: sustituye pesos y marcador tras confirmar. Recargar descarta el intento y ordena los objetos. Copias separadas del laboratorio.',
    method: '¿Cómo se decide?', methodText: 'Guía y chancla comparten integrador y obstáculos. Una “esquiva” compara el lanzamiento con una mosca inmóvil en la posición inicial; no demuestra que la política causara la huida. Ya podía estar caminando o volando.',
    senses: 'No lee tu puntería', sensesText: 'El controlador recibe 49 atributos de actividad del circuito FlyWire y 8 medidas visuales/corporales construidas a partir del presente y el pasado. No recibe fuerza, puntería ni trayectoria futura. El movimiento libre está programado; física y controlador no son una mosca biológicamente validada.',
    evaluation: 'Entrenamiento y evaluación', evaluationText: 'Paquete con {episodes} episodios de entrenamiento. En {total} lanzamientos reservados por controlador, recibió {hits} impactos, frente a {previousHits} de la versión anterior. De {threats} amenazas, evitó {dodges}; versión anterior: {previous}; acciones aleatorias: {random}. Pesos congelados, una semilla de entrenamiento, sin movimiento inicial. Resultados exploratorios, no garantía de juego ni validación biológica.',
    report: 'Informe y pesos publicados', audit: 'Código de entrenamiento', controls: 'Controles', resumeHint: 'Continúa para lanzar.',
  },
};
