import { getLocale } from '../js/i18n.js';

const copy = {
  pt: {
    gameSource: 'Palpite local · política congelada · sem dinheiro real',
    title: 'Sua mosca', escapes: 'Fugas', deaths: 'Mortes', ratio: 'Fugas / mortes', overall: 'Sobrevivência total',
    life: 'Vida atual', best: 'Melhor vida', manage: 'Aprendizado e backups', saved: 'Salvo neste navegador',
    fresh: 'Mosca nova · salvamento automático', saving: 'Salvando…', error: 'Não foi possível salvar. Exporte um backup antes de sair.',
    note: 'O aprendizado continua entre visitas. O navegador pode apagar dados locais: exporte um backup. Retomamos entre arremessos, não no meio de um movimento.',
    pretrained: 'Usar pré-treinada', export: 'Exportar aprendizado', import: 'Importar backup', clear: 'Limpar placar',
    erase: 'Apagar aprendizado', confirmErase: 'Apagar os pesos aprendidos e o placar? Os pontos do jogo serão mantidos. Exporte um backup se quiser recuperar esta mosca.',
    confirmReplace: 'Substituir o aprendizado atual? Exporte antes se quiser guardar sua mosca.', confirmStats: 'Zerar apenas o placar? Os pesos e o treino serão preservados.',
    mode: 'Experiência', lab: 'Laboratório', game: 'Palpites · só pontos', points: 'pontos', stake: 'Pontos por palpite', prediction: 'Próximo arremesso',
    escape: 'Ela escapa', hit: 'Ela é atingida', bet: 'Confirmar e assistir', resetPoints: 'Repor 1.000 pontos',
    confirmPoints: 'Recomeçar seu placar de palpites com 1.000 pontos gratuitos?',
    gameNote: 'Pontos gratuitos, locais e sem valor real. Acerto devolve 2× o valor escolhido; erro perde esse valor. As duas opções não têm necessariamente a mesma chance. Sem compras, saques ou ranking. O palpite é fechado antes do cálculo; a política não aprende nessa rodada.',
    ready: 'Escolha um palpite para iniciar.', pending: 'Palpite fechado · resultado ao fim da animação', win: 'Acertou', loss: 'Não foi desta vez',
    intense: 'Impactos intensos', effects: 'Esmagamento e fluido verde são efeitos estilizados, não anatomia ou hemolinfa fiel.',
    roam: 'Tempo livre entre arremessos', free: 'Área 32 × 32 · caminhar, girar, decolar, dirigir o salto e pousar. Colisores simplificados; folhas decorativas.',
    actions: ['Esperar', 'Inclinar à esquerda', 'Inclinar à direita', 'Decolar', 'Avançar', 'Girar à esquerda', 'Girar à direita', 'Pousar'],
    profileNote: 'A pré-treinada usa este mesmo protocolo e tem relatório público de avaliação. Não é uma mosca biológica nem uma garantia de sobrevivência.',
    gameStats: 'Placar do laboratório; palpites não entram nestes totais.',
  },
  en: {
    gameSource: 'Local prediction · frozen policy · no real money',
    title: 'Your fly', escapes: 'Escapes', deaths: 'Deaths', ratio: 'Escapes / deaths', overall: 'Overall survival', life: 'Current life', best: 'Best life',
    manage: 'Learning and backups', saved: 'Saved in this browser', fresh: 'New fly · automatic saving', saving: 'Saving…', error: 'Could not save. Export a backup before leaving.',
    note: 'Learning continues between visits. Browser data can be cleared: export a backup. Resume happens between throws, not mid-movement.',
    pretrained: 'Use pretrained fly', export: 'Export learning', import: 'Import backup', clear: 'Clear statistics', erase: 'Erase learning',
    confirmErase: 'Erase learned weights and statistics? Game points are kept. Export a backup to keep this fly.', confirmReplace: 'Replace current learning? Export first to keep your fly.', confirmStats: 'Clear statistics only? Learned weights and training are kept.',
    mode: 'Experience', lab: 'Laboratory', game: 'Predictions · points only', points: 'points', stake: 'Points per prediction', prediction: 'Next throw', escape: 'She escapes', hit: 'She gets hit', bet: 'Confirm and watch', resetPoints: 'Refill 1,000 points', confirmPoints: 'Restart your prediction score with 1,000 free points?',
    gameNote: 'Free local points with no real value. A correct prediction returns 2× the stake; a wrong one loses it. Outcomes are not necessarily equally likely. No purchases, cash-out or leaderboard. Prediction locks before calculation; learning is frozen for the round.',
    ready: 'Choose a prediction to start.', pending: 'Prediction locked · result at the end', win: 'Correct', loss: 'Not this time',
    intense: 'Intense impacts', effects: 'Crushing and green fluid are stylized effects, not faithful anatomy or hemolymph.', roam: 'Free time between throws', free: '32 × 32 arena · walk, turn, take off, steer jumps and land. Simplified colliders; decorative leaves.',
    actions: ['Wait', 'Lean left', 'Lean right', 'Take off', 'Move forward', 'Turn left', 'Turn right', 'Land'],
    profileNote: 'The pretrained policy uses this protocol and has a public evaluation report. It is not a biological fly or a survival guarantee.', gameStats: 'Laboratory statistics; predictions do not count toward these totals.',
  },
  es: {
    gameSource: 'Predicción local · política congelada · sin dinero real',
    title: 'Tu mosca', escapes: 'Escapes', deaths: 'Muertes', ratio: 'Escapes / muertes', overall: 'Supervivencia total', life: 'Vida actual', best: 'Mejor vida',
    manage: 'Aprendizaje y copias', saved: 'Guardado en este navegador', fresh: 'Mosca nueva · guardado automático', saving: 'Guardando…', error: 'No se pudo guardar. Exporta una copia antes de salir.',
    note: 'El aprendizaje continúa entre visitas. El navegador puede borrar los datos: exporta una copia. Se retoma entre lanzamientos, no a mitad del movimiento.',
    pretrained: 'Usar preentrenada', export: 'Exportar aprendizaje', import: 'Importar copia', clear: 'Borrar estadísticas', erase: 'Borrar aprendizaje', confirmErase: '¿Borrar pesos aprendidos y estadísticas? Los puntos se conservan. Exporta una copia para conservar esta mosca.', confirmReplace: '¿Reemplazar el aprendizaje actual? Exporta primero para conservar tu mosca.', confirmStats: '¿Borrar solo estadísticas? Se conservan los pesos y el entrenamiento.',
    mode: 'Experiencia', lab: 'Laboratorio', game: 'Predicciones · solo puntos', points: 'puntos', stake: 'Puntos por predicción', prediction: 'Próximo lanzamiento', escape: 'Escapa', hit: 'Recibe el golpe', bet: 'Confirmar y ver', resetPoints: 'Reponer 1.000 puntos', confirmPoints: '¿Reiniciar con 1.000 puntos gratuitos?',
    gameNote: 'Puntos gratuitos y locales, sin valor real. Un acierto devuelve 2× los puntos elegidos; un error los pierde. Los resultados no tienen necesariamente la misma probabilidad. Sin compras, retiros ni ranking. La predicción se cierra antes del cálculo y el aprendizaje se congela.',
    ready: 'Elige una predicción para empezar.', pending: 'Predicción cerrada · resultado al final', win: 'Acertaste', loss: 'Esta vez no', intense: 'Impactos intensos', effects: 'El aplastamiento y el fluido verde son efectos estilizados, no anatomía o hemolinfa fiel.', roam: 'Tiempo libre entre lanzamientos', free: 'Arena de 32 × 32 · caminar, girar, despegar, dirigir el salto y aterrizar. Colisiones simplificadas; hojas decorativas.',
    actions: ['Esperar', 'Inclinar a la izquierda', 'Inclinar a la derecha', 'Despegar', 'Avanzar', 'Girar a la izquierda', 'Girar a la derecha', 'Aterrizar'],
    profileNote: 'La política preentrenada usa este protocolo y tiene un informe público de evaluación. No es una mosca biológica ni garantiza sobrevivir.', gameStats: 'Estadísticas del laboratorio; las predicciones no cuentan en estos totales.',
  },
};
export const ac = key => (copy[getLocale()] || copy.en)[key];
